import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import FinalCTA from "@/components/FinalCTA";

import "./globals.css";

export const metadata = {
  title: "HDN Accounting Group",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={"bg-[#f8fafc]"}>
        <Navbar />
        {children}
        <FinalCTA />
        <Footer />
      </body>
    </html>
  );
}
